//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourCar.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Members = new HashSet<Member>();
        }
    
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<double> AppearedAbility { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> NumberOfPost { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> PostLimitation { get; set; }
    
        public virtual Type_Of_Account Type_Of_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
